# Generated by Django 5.2.10 on 2026-01-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
